<h2 class="mt-4">Riwayat Transaksi</h2>
<div class="table-responsive my-4">
    <table id="transactionsTable" class="display table table-striped table-hover">
        <thead>
            <tr>
                <th>ID Order</th>
                <th>Film</th>
                <th>Jam Tayang</th>
                <th>No. Kursi</th>
                <th>Total Pembayaran</th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>