<!DOCTYPE html>
<html data-bs-theme="dark">

<head>
    <title>Pesan Tiket Bioskop</title>
    <!-- Include Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Include DataTables CSS -->
    <link href="https://cdn.datatables.net/v/bs5/dt-2.0.7/datatables.min.css" rel="stylesheet">
    <!-- Font Awesome for payment icon -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
        .screen-box {
            width: 100%;
            background-color: #000;
            color: #fff;
            text-align: center;
            padding: 10px 0;
            margin-bottom: 20px;
            font-weight: bold;
        }

        .seat-button {
            width: 50px;
            height: 50px;
            margin: 5px;
            text-align: center;
        }

        .aisle {
            width: 20px;
            height: 50px;
            margin: 5px;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?php echo $this->basePath(); ?>">NontonPilem</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="<?php echo $this->basePath()?>/">Beranda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo $this->basePath()?>/application/riwayat">Riwayat Pembayaran</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-lg">
        <?php echo $this->content; ?>
    </div>

    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- Include Bootstrap 5 JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
    </script>
    <!-- Include DataTables JS -->
    <script src="https://cdn.datatables.net/v/bs5/dt-2.0.7/datatables.min.js"></script>
    <!-- Include SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Custom JS -->
    <script>
        $(document).ready(function () {
            var selectedMovieId, selectedMovieName, selectedprice, selectedplaytime, orderID;
            var selectedSeats = [];

            // Datatables initialization
            $('#transactionsTable').DataTable({
                "ajax": {
                    "url": "<?php echo $this->basePath()?>/application/api/load-order", // Pastikan URL ini benar
                    "type": "POST",
                    "data": {
                        "token": "hfjdu36498"
                    },
                    "dataSrc": function (json) {
                        // Debug: Memeriksa struktur respon
                        console.log(json);
                        if (json && json.data) {
                            return json.data;
                        } else {
                            console.error("Data not found in response:", json);
                            return [];
                        }
                    }
                },
                "columns": [
                    { "data": "id_order" },
                    { "data": "nama_film" },
                    { "data": "jam_tayang" },
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            // Memperpendek nomor kursi menjadi maksimal 5 karakter
                            if (row.no_duduk.length > 30) {
                                return row.no_duduk.substring(0, 5) + '...';
                            } else {
                                return row.no_duduk;
                            }
                        }
                    },
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            return 'Rp. ' + (row.harga_tiket * row.no_duduk.split(',').length).toLocaleString();
                        }
                    },
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            if (row.deskripsi === 'Menunggu Pembayaran') {
                                return '<button class="btn btn-primary complete-payment" data-transaction-id="' + row.id_order + '">Selesaikan Pembayaran</button>';
                            } else {
                                return '<button class="btn btn-success btn-secondary" disabled>Selesai</button>';
                            }
                        }
                    }
                ]
            });

            // Menyelesaikan payment dari tabel histori
            $('#transactionsTable').on('click', '.complete-payment', function () {
                var transactionId = $(this).data('transaction-id');
                Swal.fire({
                    title: 'Selesaikan Pembayaran',
                    text: 'Apakah Anda yakin ingin menyelesaikan pembayaran untuk transaksi ini?',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Ya, Selesaikan!',
                    cancelButtonText: 'Batal'
                }).then((result) => {
                    if (result.isConfirmed) {
                        // Implementasi logika penyelesaian pembayaran
                        $.ajax({
                            url: '<?php echo $this->basePath()?>/application/api/update-order',
                            method: 'POST',
                            data: {
                                token: 'hfjdu36498',
                                id_order: transactionId
                            },
                            success: function (response) {
                                Swal.fire(
                                    'Berhasil!',
                                    'Pembayaran telah diselesaikan.',
                                    'success'
                                );
                                $('#transactionsTable').DataTable().ajax.reload();
                            },
                            error: function (xhr, status, error) {
                                Swal.fire(
                                    'Error!',
                                    'Terjadi kesalahan saat menyelesaikan pembayaran.',
                                    'error'
                                );
                            }
                        });
                    }
                });
            });

            // Mengambil data film dari API
            $.ajax({
                url: '<?php echo $this->basePath()?>/application/api/load-list',
                method: 'POST',
                data: {
                    token: 'asdb212',
                },
                dataType: 'json',
                success: function (response) {
                    var movies = response.data;
                    // Membangun daftar film
                    movies.forEach(function (movie) {
                        var movieItem = `
                            <div class="col-lg-3 col-md-4 col-sm-12 mb-4">
                                <div class="card">
                                    <img src="${movie.film_image}" class="card-img-top" alt="Movie Image">
                                    <div class="card-body">
                                        <h5 class="card-title">${movie.nama_film}</h5>
                                        <p class="card-text">Harga Tiket: ${movie.harga_tiket} <br> Jam Tayang: ${movie.jam_tayang}</p>
                                        <div class="d-grid gap-2">
                                            <button class="btn btn-outline-primary select-movie" 
                                                data-movie-id="${movie.id_film}"
                                                data-price="${movie.harga_tiket}"
                                                data-playtime="${movie.jam_tayang}"
                                                data-movie-name="${movie.nama_film}"
                                                >Pilih</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        `;
                        $('#movieList').append(movieItem);
                    });
                },
                error: function (xhr, status, error) {
                    console.error(error);
                    Swal.fire({
                        title: "Galat",
                        text: "Terjadi kesalahan dalam mengambil data film.",
                        icon: "error",
                        timer: 3000,
                        timerProgressBar: true,
                    });
                }
            });

            // Event delegation untuk menangani event memilih film
            $('#movieList').on('click', '.select-movie', function () {
                var movieId = $(this).data('movie-id');
                selectedprice = $(this).data('price');
                selectedplaytime = $(this).data('playtime');
                selectedMovieName = $(this).data('movie-name');

                // Memeriksa apakah film yang dipilih sama dengan film yang sudah dipilih sebelumnya
                if (selectedMovieId === movieId) {
                    $(this).removeClass('btn-primary').addClass('btn-outline-primary');
                    selectedMovieId = null;
                    selectedMovieName = null;
                    selectedplaytime = null;
                    selectedprice = 0;
                } else {
                    $('.select-movie').removeClass('btn-primary').addClass('btn-outline-primary');
                    $(this).removeClass('btn-outline-primary').addClass('btn-primary');
                    selectedMovieId = movieId;
                }

                // Menampilkan nama film yang dipilih pada tabel
                $('#film-selected').text(selectedMovieName);
                // Menampilkan harga film yang dipilih pada tabel
                $('#price-selected').text('Rp. ' + selectedprice);
                // Menampilkan jam tayang film yang dipilih pada tabel
                $('#playtime-selected').text(selectedplaytime);
                // Menampilkan total harga
                $('#total-price').text("Rp. " + hitungTotalHarga());
            });

            // Event untuk pemilihan kursi
            $('.seat-button').on('click', function () {
                const seatNumber = $(this).data('seat');
                if (!selectedSeats.includes(seatNumber)) {
                    selectedSeats.push(seatNumber);
                    $(this).removeClass('btn-outline-secondary').addClass('btn-success');
                } else {
                    selectedSeats = selectedSeats.filter(seat => seat !== seatNumber);
                    $(this).removeClass('btn-success').addClass('btn-outline-secondary');
                }
                console.log(selectedSeats);
                // Menampilkan kursi terpilih
                $('#seats-selected').text(selectedSeats);
                // Menampilkan total harga
                $('#total-price').text("Rp. " + hitungTotalHarga());
            });

            $('#payButton').on('click', function () {
                if (!selectedMovieId) {
                    Swal.fire({
                        title: "Galat",
                        text: "Silahkan pilih film terlebih dahulu",
                        icon: "warning",
                        timer: 3000,
                        timerProgressBar: true,
                    });
                } else if (selectedSeats.length === 0) {
                    Swal.fire({
                        title: "Galat",
                        text: "Silahkan pilih kursi terlebih dahulu",
                        icon: "warning",
                        timer: 3000,
                        timerProgressBar: true,
                    });
                } else {
                    Swal.fire({
                        title: "Apakah anda ingin melanjutkan ke pembayaran?",
                        icon: "question",
                        showDenyButton: true,
                        showCancelButton: false,
                        confirmButtonText: "Ya",
                        denyButtonText: `Batal`
                    }).then((result) => {
                        /* Read more about isConfirmed, isDenied below */
                        if (result.isConfirmed) {
                            $('#payModal').modal('show');
                            submitData();
                        } else if (result.isDenied) {
                            // Cancel function
                        }
                    });

                    // alert('Melanjutkan ke pembayaran untuk film: ' + $('#film-selected').text() +
                    //     ', harga: ' + selectedprice + ', jam tayang: ' + selectedplaytime +
                    //     ', kursi: ' +
                    //     selectedSeats.join(', '));
                }
            });

            $('.close-modal').on('click', function () {
                clearData();
            });

            function hitungTotalHarga() {
                var count = selectedprice * selectedSeats.length;
                return count;
            }

            function submitData() {
                var seats = selectedSeats.toString();

                $.ajax({
                    url: '<?php echo $this->basePath()?>/application/api/create-order',
                    type: "POST",
                    dataType: 'json',
                    data: {
                        token: 'hfjdu36498',
                        id_film: selectedMovieId,
                        no_duduk: seats,
                        next_id: orderID,
                    },
                    success: function (response) {
                        var res = response.data;
                        console.log(res);

                        // Menampilkan id bayar yang dipilih pada tabel
                        $('#id-checkout').text(res.id_order);
                        // Menampilkan nama film yang dipilih pada tabel
                        $('#film-checkout').text(res.nama_film);
                        // Menampilkan harga film yang dipilih pada tabel
                        $('#price-checkout').text('Rp. ' + selectedprice);
                        // Menampilkan jam tayang film yang dipilih pada tabel
                        $('#playtime-checkout').text(selectedplaytime);
                        // Menampilkan kursi yang dipilih pada tabel
                        $('#seats-checkout').text(selectedSeats);
                        // Menampilkan total harga
                        $('#total-price-checkout').text("Rp. " + hitungTotalHarga());
                    },
                    error: function (xhr, status, error) {
                        console.error('Error:', error);
                    }
                });
            }

            $('.pay-now').on('click', function () {
                var id = $('#id-checkout').text();
                console.log(id);

                $.ajax({
                    url: '<?php echo $this->basePath()?>/application/api/update-order',
                    type: "POST",
                    dataType: 'json',
                    data: {
                        token: 'hfjdu36498',
                        id_order: id
                    },
                    success: function (response) {
                        var res = response.data;
                        console.log(res);

                        Swal.fire({
                            title: "Pembayaran Berhasil",
                            text: "Pembayaran untuk ID Order : "+id+" berhasil dilakukan. ",
                            icon: "success",
                            timer: 3000,
                            timerProgressBar: true,
                            didClose: () => {
                                window.location.reload();
                            }
                        });
                    },
                    error: function (xhr, status, error) {
                        console.error('Error:', error);
                    }
                });
                
                clearData();
            });

            function clearData() {
                $('.select-movie').removeClass('btn-primary').addClass('btn-outline-primary');
                $('.seat-button').removeClass('btn-success').addClass('btn-outline-secondary');
                selectedMovieId = null;
                selectedMovieName = null;
                selectedplaytime = null;
                selectedprice = 0;
                selectedSeats = [];

                // Menampilkan nama film yang dipilih pada tabel
                $('#film-selected').text(selectedMovieName);
                // Menampilkan harga film yang dipilih pada tabel
                $('#price-selected').text('Rp. ' + selectedprice);
                // Menampilkan jam tayang film yang dipilih pada tabel
                $('#playtime-selected').text(selectedplaytime);
                // Menampilkan total harga
                $('#total-price').text("Rp. " + hitungTotalHarga());
                // Menampilkan kursi terpilih
                $('#seats-selected').text(selectedSeats);

                console.log('Data Flushed :', selectedMovieId, selectedMovieName, selectedplaytime, selectedprice, selectedSeats);
            }
        });
    </script>
</body>

</html>
