<!DOCTYPE html>
<html data-bs-theme="dark">

<head>
    <title>Pesan Tiket Bioskop</title>
    <!-- Include Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Include DataTables CSS -->
    <link href="https://cdn.datatables.net/v/bs5/dt-2.0.7/datatables.min.css" rel="stylesheet">
    <!-- Font Awesome for payment icon -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
        .seat-button {
            margin: 5px;
            width: 60px;
            height: 60px;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?php echo $this->basePath(); ?>">NontonPilem</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Beranda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Riwayat Pembayaran</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-lg">
        <?php echo $this->content; ?>
    </div>

    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- Include Bootstrap 5 JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">
    </script>
    <!-- Include DataTables JS -->
    <script src="https://cdn.datatables.net/v/bs5/dt-2.0.7/datatables.min.js"></script>
    <!-- Custom JS -->
    <script>
        $(document).ready(function () {
            var selectedMovieId, selectedMovieName, selectedprice, selectedplaytime, id_order;
            var selectedSeats = [];

            // Mengambil data film dari API
            $.ajax({
                url: '<?php echo $this->basePath()?>/application/api/load-list',
                method: 'POST',
                data: {
                    token: 'asdb212',
                },
                dataType: 'json',
                success: function (response) {
                    var movies = response.data;
                    // Membangun daftar film
                    movies.forEach(function (movie) {
                        var movieItem = `
                            <div class="col-lg-3 col-md-4 col-sm-12 mb-4">
                                <div class="card">
                                    <img src="${movie.film_image}" class="card-img-top" alt="Movie Image">
                                    <div class="card-body">
                                        <h5 class="card-title">${movie.nama_film}</h5>
                                        <p class="card-text">Harga Tiket: ${movie.harga_tiket} <br> Jam Tayang: ${movie.jam_tayang}</p>
                                        <div class="d-grid gap-2">
                                            <button class="btn btn-outline-primary select-movie" 
                                                data-movie-id="${movie.id_film}"
                                                data-price="${movie.harga_tiket}"
                                                data-playtime="${movie.jam_tayang}"
                                                data-movie-name="${movie.nama_film}"
                                                >Pilih</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        `;
                        $('#movieList').append(movieItem);
                    });
                },
                error: function (xhr, status, error) {
                    console.error(error);
                    alert('Terjadi kesalahan saat mengambil data film.');
                }
            });

            // Event delegation untuk menangani event memilih film
            $('#movieList').on('click', '.select-movie', function () {
                var movieId = $(this).data('movie-id');
                selectedprice = $(this).data('price');
                selectedplaytime = $(this).data('playtime');
                selectedMovieName = $(this).data('movie-name');

                // Memeriksa apakah film yang dipilih sama dengan film yang sudah dipilih sebelumnya
                if (selectedMovieId === movieId) {
                    $(this).removeClass('btn-primary').addClass('btn-outline-primary');
                    selectedMovieId = null;
                    selectedMovieName = null;
                    selectedplaytime = null;
                    selectedprice = 0;
                } else {
                    $('.select-movie').removeClass('btn-primary').addClass('btn-outline-primary');
                    $(this).removeClass('btn-outline-primary').addClass('btn-primary');
                    selectedMovieId = movieId;
                }

                // Menampilkan nama film yang dipilih pada tabel
                $('#film-selected').text(selectedMovieName);
                // Menampilkan harga film yang dipilih pada tabel
                $('#price-selected').text('Rp. ' + selectedprice);
                // Menampilkan jam tayang film yang dipilih pada tabel
                $('#playtime-selected').text(selectedplaytime);
                // Menampilkan total harga
                $('#total-price').text("Rp. " + hitungTotalHarga());
            });

            // Event untuk pemilihan kursi
            $('.seat-button').on('click', function () {
                const seatNumber = $(this).data('seat');
                if (!selectedSeats.includes(seatNumber)) {
                    selectedSeats.push(seatNumber);
                    $(this).removeClass('btn-outline-secondary').addClass('btn-success');
                } else {
                    selectedSeats = selectedSeats.filter(seat => seat !== seatNumber);
                    $(this).removeClass('btn-success').addClass('btn-outline-secondary');
                }
                console.log(selectedSeats);
                // Menampilkan kursi terpilih
                $('#seats-selected').text(selectedSeats);
                // Menampilkan total harga
                $('#total-price').text("Rp. " + hitungTotalHarga());
            });

            $('#payButton').on('click', function () {
                if (!selectedMovieId) {
                    alert('Silakan pilih film terlebih dahulu!');
                } else if (selectedSeats.length === 0) {
                    alert('Silakan pilih kursi terlebih dahulu!');
                } else {
                    alert('Melanjutkan ke pembayaran untuk film: ' + $('#film-selected').text() +
                        ', harga: ' + selectedprice + ', jam tayang: ' + selectedplaytime +
                        ', kursi: ' +
                        selectedSeats.join(', '));
                    $('#payModal').modal('show');
                    checkID();
                }
            });

            function hitungTotalHarga() {
                var count = selectedprice * selectedSeats.length;
                return count;
            }

            function checkID() {
                $.ajax({
                    url: '<?php echo $this->basePath()?>/application/api/load-order', // ini API nya
                    type: "GET",
                    dataType: 'json',
                    data: {
                        token: 'hfjdu36498',
                    },
                    success: function (response) {
                        var id_order = response.data;
                        var jumlahData = Array.isArray(id_order) ? id_order.length : 0;
                        console.log('ID Bayar: ' + id_order);
                        console.log('Jumlah data: ' + jumlahData);
                    },
                    error: function (xhr, status, error) {
                        console.error('Error:', error);
                    }
                });
            }
        });
    </script>
</body>

</html>
